services:
  nginx:
    image: nginx:inc
    build: ./nginx
    volumes:
      - ./nginx/:/usr/share/nginx/html
    ports:
      - 80:80
    container_name: nginx_container
    networks:
      - tor_network
  
  tor:
    image: tor:inc
    build: ./tor
    volumes:
      - tor:/home
    container_name: tor_container
    depends_on:
      - nginx
    networks:
      - tor_network

networks:
  tor_network:
    driver: bridge

volumes:
  nginx:
  tor: