services:
  nginx:
    image: nginx:inc
    build: ./nginx
    volumes:
      - nginx:/home
    ports:
      - 8089:80
    container_name: nginx_container
  
  tor:
    image: tor:inc
    build: ./tor
    volumes:
      - tor:/home
    container_name: tor_container

volumes:
  nginx:
  tor: